### ISSUE TITLE
Multiple tags for 3.3.1

### ISSUE THREAD

**Issue by gastonelhordoy** [Acquisio/bootstrap-stylus#86]
Hi guys, this might not be exactly an issue, but it is somehow confusing. Why there are 3 different tags for version 3.3.1 (two of them actually with a major set to 4)?

https://github.com/Acquisio/bootstrap-stylus/tree/3.1.1
https://github.com/Acquisio/bootstrap-stylus/tree/4.0.0
https://github.com/Acquisio/bootstrap-stylus/tree/4.0.1

**Comment by maxmx** [comment]
We merged a breaking change in bootstrap stylus before releasing 4.0.0. Version was upgraded to 4.0.0 to support semver as not to break the implementation of all existing codebases that were using bs-stylus.

It also happenned numerous times in the past where we would release a matching version of Bootstrap, then it would contain bugs, this meant deleting the release and re-releasing it, which is bad practices as in theory it could mean that two different computers that run a project using BS Stylus, could have two different version of the library is one has npm-installed after a breaking-tag delete and re-release.

Hopefully that makes enough sense.

You can see the discussion in https://github.com/Acquisio/bootstrap-stylus/issues/72 if you are curious.

**Comment by gastonelhordoy** [comment]
Thanks for the clarification! What if you add a *VERY* short changelog file and link it from the README? in that way these things stay documented for everyone to easily see them.

**Comment by gastonelhordoy** [comment]
BTW, why not creating 3.1.1.1 and 3.1.1.2 releases like in previous cases as well? I'm just wondering what are you gonna do when BS 4 comes out?

**Comment by maxmx** [comment]
Right makes sense.

as for x.x.x.x versions I stoped doing it because of:

https://github.com/Acquisio/bootstrap-stylus/issues/53

For the second part of you question, you can see this repo as : Boostrap 3.3.1 for Stylus, then someday it will be Bootstrap 4.0.0 for Stylus, the internal version is not important.

The release version is hard to match with the official version as explained in the example scenario I gave.

Lets say you are working and using 3.3.1 on your computer at the office.
Then we do a breaking change on 3.3.1 while trying to fix a bug.
We re-release 3.3.1 because we want to be on the version version as Bootstrap official.

When you get home a few days later and you did not realize that 3.3.1 was re-released, and you checkout your project on your home computer and then do npm install and for some reason nothing works because the release is currently bugged because it managed to pass our code-reviewing eyes, you wont be really happy.

Same goes for why I ended up bumping the version from 3.3.1 to 4 because I realized that if I re-released version 3.3.1 with the included breaking changes (a folder was moved/renamed) every user out there using the library would have had some work, however minor it is to do to make their project work again.

The semver system, if followed guarantees that no breaking changes will be introduced in a minor or patch version. Hence why I bumped the major version.

Hope this answers everything!

**Comment by gastonelhordoy** [comment]
Gotcha, I didn't understand why semver would be broken adding a fourth digit. I get now it is just because of the idea behind major, minor and patch version numbers.
Thanks for the clarification!
